version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
      - /_docker/nginx/certs:/etc/nginx/certs
    ports:
      - 8000:80
    depends_on:
      - app
    container_name: symfony_shop_nginx

  app:
    build:
      args:
        user: docker-user
        uid: 1000
      context: .
      dockerfile: ./_docker/app/Dockerfile
    volumes:
      - ./:/var/www
      - ./_docker/app/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - db
    container_name: symfony_shop_app
    environment:
      - PHP_IDE_CONFIG=serverName=shopservername
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
  db:
    image: mysql:8.0
    restart: always
    tty: true
    volumes:
      - ./_docker/tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: symfony_shop
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8101:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password
    container_name: symfony_shop_mysql